### ISSUE TITLE
XML External Entity (XXE) Injection vulnerability (CVSS score 9.8)

### ISSUE THREAD

**Issue by KrisGerhard** [diabolicallabs/vertx-cron#17]
Seems to be fixed in the latest quartz version.

**Introduced via a `quartz` dependency**
`com.diabolicallabs:vertx-cron@3.8.5 › org.quartz-scheduler:quartz@2.2.2 › c3p0:c3p0@0.9.1.1`

**More info**
https://app.snyk.io/vuln/SNYK-JAVA-C3P0-461017

**Comment by diabolicallabs** [comment]
Updated quartz to 2.3.2 and deployed version 3.9.1 to maven central. Thanks.
