### ISSUE TITLE
Jobs called twice

### ISSUE THREAD

**Issue by rvraaphorst** [diabolicallabs/vertx-cron#4]
Hi,

Thx for the vertx-cron library, very easy to use and very useful. But sometimes a job is called twice. 
I suppose that it's a rounding issue somewhere, maybe even in the Quartz library. It's annoying though, because in my case I'd send the same email to the same user twice :(

I've setup 3 jobs that just log the time.: One every 30 seconds, one every minute and one every two minutes. 
The bold lines show the double calls. As can bee seen, they're triggered just a millisecond (or sometimes two) before, and then again.

23:08:00.002 [vert.x-eventloop-thread-5] INFO  nl.app.CronVerticle - In /cron/job-1 - every minute
23:08:00.003 [vert.x-eventloop-thread-5] INFO  nl.app.CronVerticle - In /cron/job-2 - every 2 minutes
23:08:00.004 [vert.x-eventloop-thread-5] INFO  nl.app.CronVerticle - In /cron/job-30 - every 30 seconds

23:08:30.006 [vert.x-eventloop-thread-5] INFO  nl.app.CronVerticle - In /cron/job-30 - every 30 seconds

**23:08:59.999 [vert.x-eventloop-thread-5] INFO  nl.app.CronVerticle - In /cron/job-1 - every minute**
23:09:00.000 [vert.x-eventloop-thread-5] INFO  nl.app.CronVerticle - In /cron/job-30 - every 30 seconds
**23:09:00.001 [vert.x-eventloop-thread-5] INFO  nl.app.CronVerticle - In /cron/job-1 - every minute**

23:09:30.004 [vert.x-eventloop-thread-5] INFO  nl.app.CronVerticle - In /cron/job-30 - every 30 seconds
**23:09:59.999 [vert.x-eventloop-thread-5] INFO  nl.app.CronVerticle - In /cron/job-2 - every 2 minutes**
23:10:00.000 [vert.x-eventloop-thread-5] INFO  nl.app.CronVerticle - In /cron/job-1 - every minute
**23:10:00.001 [vert.x-eventloop-thread-5] INFO  nl.app.CronVerticle - In /cron/job-2 - every 2 minutes**
23:10:00.001 [vert.x-eventloop-thread-5] INFO  nl.app.CronVerticle - In /cron/job-30 - every 30 seconds

Here are their configurations:

` {
          "cron_expression": "*/30 * * * * ?",
          "address": "/cron/job-30",
          "action": "send"
        },
        {
          "cron_expression": "0 0/1 * 1/1 * ? *",
          "address": "/cron/job-1",
          "action": "send"
        },
        {
          "cron_expression": "0 0/2 * 1/1 * ? *",
          "address": "/cron/job-2",
          "action": "send"
        }`

**Comment by diabolicallabs** [comment]
Thank you for the report. I shall attend to it directly.

**Comment by diabolicallabs** [comment]
I was not able to reproduce this. How long does it take before you see duplicates? Perhaps you can provide the complete test case.

Also, kindly ensure that you are starting the cron job only once. If there are multiple instances of the verticle from which you are setting up the cron job, it will also instantiate the job that many times. This can happen if you deploy the verticle to multiple members of a cluster or you deploy your verticle with DeploymentOptions.setInstances(int instances).

I've done that myself a number of times and got duplicate messages.

You an avoid this by ensuring that the vertical calling cron is deployed only once across the cluster. You can also use a system wide lock when setting up the job, then you don't have to worry about the number of deployed instances.

```
    vertx.sharedData().getLock("cronJobName", lockHandler -> {
     if (lockHandler.succeeded() {
        //We will only get the lock once across the cluster
        vertx.eventBus().send("someCronAddress", event, handler -> {
          [...]
        });
      }
    });
```

I should probably add this to the documentation.

**Comment by diabolicallabs** [comment]
I added the warning about multiple instances to the documentation
