### ISSUE TITLE
Message should be object

### ISSUE THREAD

**Issue by Zwergal** [diabolicallabs/vertx-cron#5]
The message in the schedule event should be an object as in the readme:

    {
        "title": "A Cron Scheduler schedule message",
        "type":"object",
        "properties": {
            "cron_expression": {"type": "string"},
            "timezone_name": {"type": "string"},
            "address": {"type": "string"},
            "message": {"type": "object"},
            "action": {"enum": ["send", "publish"]},
            "result_address": {"type": "string"}
        },
        "required": ["cron_expression", "address"]
    }

But in the code it is:
`Object scheduledMessage = message.getString("message");` (Line 61)

which is wrong and leads to an exception.
I think this should be:

`Object scheduledMessage = message.getJsonObject("message");`

**Comment by diabolicallabs** [comment]
Fixed in version 3.3.0
