### ISSUE TITLE
Unscheduling jobs

### ISSUE THREAD

**Issue by erwindeg** [diabolicallabs/vertx-cron#6]
Is there a way to get a list of scheduled jobs and to unschedule them?

**Comment by diabolicallabs** [comment]
As of now there is no way. I assume that you'd like it. We'll look at putting that in the next version.

**Comment by erwindeg** [comment]
For now, I use the CronObservable and store the returned subscriptions in a map. This allows me to unsubscribe them by calling the unsubscribe() method.

**Comment by diabolicallabs** [comment]
I added support for this. When scheduling an event, and ID will be returned. If you want to cancel, just publish that ID to cron.cancel.
